import random #allows for us to import random number.

guessesTaken = 0

print('Hello! What is your name?')
myName = input() #stores the name of the player in the variable myName.

number = random.randint(1, 50) #generates a random number between 1 and 50
print('Well, ' + myName + ', I am thinking of a number between 1 and 50. You will have 6 tries to guess it correctly.') #instructions for player

for i in range(6):  #tells the computer to iterate the guessing lopp 6 times.
    print('Take a guess.')
    guess = input()
    guess = int(guess)
    #stores the players guesses

    if guess < number:
        print('Your guess is too low. Try again.')
        #if guess is too low

    if guess > number:
        print('Your guess is too high. Try again')
        #if guess is too high


    if guess == number:
        break
    #if guess is equal to the random number

if guess == number:
    guessesTaken = str(guessesTaken)
    print('Good Job, ' + myName+ '! You guessed my number correctly!')
    #what to tell the player is the number is equal to the random number generated by the computer

if guess != number:
    number=str(number)
    print('Nope. The number I was thinking of was ' + number +'.')
    #what to tell the player if they run out of guesses to make.
